
export const LOADING = "PRODUCT.LOADING";
export const INIT_PRODUCTS = "PRODUCT.INIT_PRODUCTS";

export const EDIT_PRODUCT = "PRODUCT.EDIT_PRODUCT";
export const EDIT_BRAND = "PRODUCT.EDIT_BRAND";

export const INIT_BRANDS = "PRODUCT.INIT_BRANDS";
